language: objective-c
osx_image: xcode7.2
xcode_workspace: VirtualGameController.xcworkspace
xcode_scheme:
- VirtualGameControllerIOS
- VirtualGameControllerOSX
- VirtualGameControllerTvOS
- VirtualGameControllerWatchOS

env:
- xcode_sdk=iphonesimulator9.2
- xcode_sdk=macosx10.11
- xcode_sdk=tvos9.0
- xcode_sdk=watchos2.0
