language: objective-c
osx_image: xcode7.2
xcode_workspace: VirtualGameController.xcworkspace
matrix:
    include:
    - xcode_sdk: iphonesimulator9.2
        env: xcode_scheme=VirtualGameControllerIOS
    - xcode_sdk: macosx10.11
        env: xcode_scheme=VirtualGameControllerOSX
    - xcode_sdk: iphonesimulator9tvos9.0
        env: xcode_scheme=VirtualGameControllerTvOS
    - xcode_sdk: watchos2.0
        env: xcode_scheme=VirtualGameControllerWatchOS